set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

UNSET(CMAKE_C_FLAGS CACHE)

set(SYSTEM_DETAILS Linux)

option( IOT_BUILD_FOR_LINUX64  "Build for linux64."  ON )